### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by 92hg** [MaxxRider/Leech-Pro#45]
Bot stuck at 🔊 Now Uploading to ☁️ Cloud!!!
Even the download isn't successful looking at the size mentioned 1.19KB, while it's a 17MB file. 

Logs:-
```
Scaled to worker@0:Free by user 
Scaled to worker@1:Free by user 
 11-May-22 01:10:33 - INFO - https://file-examples.com/wp-content/uploads/2017/04/file_example_MP4_1920_18MG.mp4 [incoming_message_fn.py:79]
 11-May-22 01:10:34 - INFO - ['aria2c', '--conf-path=/app/tobrot/aria2/aria2.conf', '--allow-overwrite=true', '--daemon=true', '--enable-rpc', '--disk-cache=0', '--follow-torrent=mem', '--max-connection-per-server=16', '--min-split-size=10M', '--rpc-listen-all=false', '--rpc-listen-port=6800', '--rpc-max-request-size=1024M', '--seed-ratio=0.01', '--seed-time=1', '--max-overall-upload-limit=2M', '--split=16', '--bt-stop-timeout=600'] [download_aria_p_n.py:68]
 11-May-22 01:10:35 - INFO - 3b08741c8c1b8ab4 [download_aria_p_n.py:185]
 11-May-22 01:10:50 - INFO - Downloaded Successfully: `file_example_MP4_1920_18MG.mp4 (1.19 KiB)` 🤒 [download_aria_p_n.py:326]
 11-May-22 01:11:07 - ERROR - list index out of range [dispatcher.py:235]
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 222, in handler_worker
     await handler.callback(self.client, *args)
   File "/app/tobrot/plugins/incoming_message_fn.py", line 120, in incoming_message_f
     sagtus, err_message = await call_apropriate_function(
   File "/app/tobrot/helper_funcs/download_aria_p_n.py", line 256, in call_apropriate_function
     await upload_to_gdrive(
   File "/app/tobrot/helper_funcs/upload_to_tg.py", line 156, in upload_to_gdrive
     gUP = re.findall("\[(.*)\]", con)[0]
 IndexError: list index out of range

```

**Comment by MaxxRider** [comment]
Did u added Rclone in vars? properly???
because working fine for me

**Comment by Ajayveer9911github** [comment]
> Did u added Rclone in vars? properly??? because working fine for me

Same issue for me
.. I added "rclone.config" name var in heroku... with generated rclone config... But, in logs, Its giving Index OutOf Bound Exception...

**Comment by MaxxRider** [comment]
fill the vars correctly

**Comment by floramabel** [comment]
i Too faced the same error.. the thing is you have password protected the configuration .conf file

**Comment by floramabel** [comment]
Decrypt using rclone
